server:
  port: 9007

logging:
  #file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.kkb: debug

spring:
  redis:
    host: 110.42.216.234
    port: 6379 #canal配置
    password: 123456

canal:
  client:
    instances:
      # exmaple
      example:
        host: 127.0.0.1
        port: 11111