server:
  port: 9005

spring:
  rabbitmq:
    host: 110.42.216.234
    port: 5672
mq:
  item:
    exchange:
      update: exchange.update.item
    queue:
      update: queue.update.item
    routing:
      key: routing.update.item

mybatis-plus:
  mapper-locations: classpath*:mybatis/*/*.xml
  type-aliases-package: com.kkb.legou.*.po
  configuration:
    # 下划线驼峰转换
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  #file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.kkb: debug

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9098/oauth/token_key
