server:
  port: 9009

spring:
  redis:
    host: 110.42.216.234
    port: 6379
    password: 123456
  rabbitmq:
    host: 110.42.216.234
    port: 5672

mybatis-plus:
  mapper-locations: classpath*:mybatis/*/*.xml
  type-aliases-package: com.kkb.legou.*.po
  configuration:
    # 下划线驼峰转换
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

logging:
  #file: demo.log
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: debug
    com.kkb: debug

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9098/oauth/token_key #如果使用JWT，可以获取公钥用 于 token 的验签

mq:
  pay:
    exchange:
      order: exchange.pay.order
    queue:
      order: queue.pay.order
    routing:
      key: routing.pay.order
  order:
    exchange:
      ttl: exchange.order.ttl
      dlx: exchange.order.dlx
    queue:
      ttl: queue.order.ttl
      dlx: queue.order.dlx
    routing:
      ttl: routing.order.ttl
      dlx: routing.order.dlx
